version: '3'
services:
  app:
    build:
      dockerfile: test.dockerfile
      context: .
    image: guilhermeroque/auth-service-test
    environment:
      - DB_URL=mongodb://mongo/
      - DB_NAME=auth-service
      - DB_USERNAME=myUserAdmin
      - DB_PASSWORD=password
      - DB_HOST=mongo
      - SERVER_PORT=3000
      - SWAGGER_HOST=localhost:5000
    volumes:
      - ./src:/root/src
    ports:
      - 5000:3000
    depends_on:
      - mongo
    networks:
      - test-network

  mongo:
    build:
      dockerfile: mongodb.dockerfile
      context: .
    networks:
      - test-network

networks:
  test-network:
    driver: bridge