version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: guilhermeroque/auth-service
    env_file: .env.sample
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "myUserAdmin"
      MONGO_INITDB_ROOT_PASSWORD: "password"